# --- Minimal Mistakes 主題設定 ---

# 網站基本設定
title: "我的技术博客"
description: "一个记录学习和生活的空间"
encoding: utf-8
exclude: [README.md, Gemfile, Gemfile.lock]

# 主題設定 (使用 Gem-based theme)
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air" 

# 評論系統設定 (已填入您的 Giscus ID)
comments:
  provider: "giscus"
  giscus:
    repo: "tanboning1118/tanboning1118.github.io"
    repo_id: "R_kgDOP8rInA"
    category: "General"
    category_id: "DIC_kwDOP8rInM4CwRwq"
    mapping: "pathname"
    strict: "0"
    reactions_enabled: "1"
    emit_metadata: "0"
    input_position: "bottom"
    lang: "zh-CN"

# 作者資訊
author:
  name: "tanboning1118"
  avatar: "https://github.com/tanboning1118.png"
  bio: "美食爱好者"
  location: "Shanghai"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tanboning1118"
