# ---------------- 极简核心配置 ----------------

# 语言: zh-CN 代表简体中文
lang: zh-CN

# 网站网址 (非常重要！)
url: "https://tanboning1118.github.io"

# 网站标题
title: tanboning1118的博客

# 网站副标题
tagline: 学习与记录

# 您的名字或昵称
author: tanboning1118

# 侧边栏头像 (会自动抓取您的 GitHub 头像)
avatar: https://github.com/tanboning1118.png

# 社交链接
social:
  name: tanboning1118
  links:
    - https://github.com/tanboning1118

# ---------------- 以下为主题运行所需，无需修改 ----------------

# 时区
timezone: Asia/Shanghai

# 主题模式 (留空则跟随系统，提供深色/亮色切换)
theme_mode:

# 分页
paginate: 10

# Jekyll 核心配置
baseurl: ""

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false # 已禁用评论
      toc: true

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - "package*.json"
