# --- 网站核心配置 ---

# 网站语言，'zh-CN' 代表简体中文
lang: zh-CN

# 您的时区
timezone: Asia/Shanghai

# --- 网站基础信息 (用于SEO和页面显示) ---

# 网站主标题
title: tanboning1118的技术博客

# 网站副标题/标语，会显示在标题下方
tagline: 机器人、学习与生活随想

# 网站描述 (用于搜索引擎优化)
description: >-
  来自同济大学，一位机器人方向学生的学习笔记、技术分享与生活记录。

# 您的网站网址，非常重要！
url: "https://tanboning1118.github.io"

# --- 作者与社交信息 ---

# 您的 GitHub 用户名
github:
  username: tanboning1118

# 您的 Twitter 用户名 (如果没有可以留空或删除)
twitter:
  username: # twitter_username

# 社交信息，会显示在侧边栏和页脚
social:
  # 您的名字或昵称
  name: tanboning1118
  # 您的邮箱 (可选)
  email: your-email@example.com
  # 社交链接列表
  links:
    - https://github.com/tanboning1118 # 第一个链接会用作版权链接

# 侧边栏头像，会自动抓取您的GitHub头像
avatar: https://github.com/tanboning1118.png

# --- 功能配置 ---

# 默认主题颜色模式：light (亮色), dark (暗色)，留空则跟随系统
theme_mode:

# 文章目录功能的全局开关
toc: true

# 评论系统配置 (为您预设了 Giscus)
comments:
  provider: "giscus" # 推荐使用 Giscus，与 GitHub 深度集成
  giscus:
    repo: "tanboning1118/tanboning1118.github.io" # 您的仓库地址
    # 以下几项需要您去 Giscus 官网配置后填入
    repo_id: # 在 Giscus 官网获取
    category: # 在 Giscus 官网获取
    category_id: # 在 Giscus 官网获取
    mapping: "pathname"
    strict: "0"
    reactions_enabled: "1"
    emit_metadata: "0"
    input_position: "bottom"
    lang: "zh-CN"

# --- 分页设置 ---
paginate: 10

# --- Jekyll 核心配置 (通常无需修改) ---
baseurl: ""
kramdown:
  syntax_highlighter: rouge
collections:
  tabs:
    output: true
    sort_by: order
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - "package*.json"
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
